# имя workflow, оно будет использоваться в интерфейсе GitHub Actions
name: Main Taski Workflow
# события-триггеры, после которых должен срабатывать workflow
on:
  # Событие push возникает,
  # когда изменения исходного кода приходят на сервер GitHub
  push:
    # Отслеживаем изменения только в ветке main
    branches:
      - main
# список действий, которые должны выполниться после срабатывания триггера.
jobs:
  # Единственная задача — склонировать код 
  # и вывести в консоль дерево файлов
  checkout-and-print-tree:
    runs-on: ubuntu-latest
    steps:
      # На GitHub Actions есть готовые описания шагов, 
      # их можно использовать в своих workflow.
      # Применим готовое описание шага для получения исходного кода
      - name: Check out repository code  # Имя шага задаём сами
        # используем готовый workflow actions/checkout@v3: он клонирует 
        # текущий коммит репозитория, в котором запущен workflow (в данном случае Taski) 
        # в текущую рабочую директорию раннера. 
        uses: actions/checkout@v3  # Берём готовое решение из библиотеки GitHub Actions
      # Выполняем команду tree в текущей директории
      - name: Print project tree
        run: tree .